### ISSUE TITLE
rename time.h -> etime.h to avoid stdlib collision

### ISSUE THREAD

**Issue by no-lex** [project-imprimis/enet#2]
`time.h` is a standard library header, and this namespace collision causes issues with source code analyzers. It should be changed to a slightly different name to avoid this problem.

**Comment by acerspyro** [comment]
Here's an example of the issue in CLion:

![image](https://user-images.githubusercontent.com/4400999/83163679-4db0c800-a0d9-11ea-898d-7bbd45a42895.png)

Looking at the file ``/usr/include/c++/9/ctime``, the IDE will attempt to fetch ``time.h`` from enet instead
